accounts/urls.py
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from . import views

app_name = 'accounts'
urlpatterns = [
    path('log-in/', views.login, name='log-in'),
    path('log-out/', views.logout, name='log-out'),
    path('settings/', views.settings, name='settings'),
]

bot/urls.py
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from .views import *

app_name = 'bot'
urlpatterns = [
    path('doc/functional', bot_function_docs, name='func-docs'),
    path('list/', bot_list_view, name='bot-list'),  
    path('list/code', bot_code_list_view, name='bot-code-list'),
    path('create/', bot_create_view, name='bot-create'),
    path('update/<int:pk>', bot_update_view, name='bot-update'),
    path('delete/<int:obj_id>', bot_delete_view, name='bot-delete'),
    path('run/<int:pk>', run_bot, name='bot-run'),
    path('log/list', log_list, name='bot-log'),
    path('data/list', bot_data, name='bot-data'),
]

main/urls.py
from . import views
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
]

upt/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# import debug_toolbar
urlpatterns = [
    # path('__debug__/', include(debug_toolbar.urls)),
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
    path('', include('main.urls')),
    path('bot/', include('bot.urls')),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.contrib import auth
from django.contrib.auth.decorators import login_required


def index(request):
    return render(request, 'default/index.html')

main/templates/parts/breadcrumbs.html
<nav>
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Overview</li>
        {% if next %}
            <li class="breadcrumb-item">{{ next }}</li>
        {% endif %}
    </ol>
</nav>

main/templates/parts/content-header.html
<nav class="navbar navbar-expand navbar-light bg-white">
    <div class="navbar-brand">
        <button type="button" class="btn btn-sidebar" data-toggle="sidebar"><i class="fa fa-bars"></i>
        </button>
        <span class="pr-2"><a href="{% url 'main:index' %}">Overview</a></span>
    </div>
{#    <ul class="navbar-nav ml-auto">#}
{#        <li class="nav-item dropdown">#}
{#            <a href="#" class="nav-link dropdown-toggle" role="button"#}
{#               data-toggle="dropdown" aria-haspopup="true"#}
{#               aria-expanded="false">#}
{#                <span class="badge badge-pill badge-primary">3</span>#}
{#                <i class="far fa-bell"></i>#}
{#            </a>#}
{#            <div class="dropdown-menu dropdown-menu-right">#}
{#                <a href="" class="dropdown-item">#}
{#                    <small class="dropdown-item-title">Lorem ipsum (today)</small>#}
{#                    <br>#}
{#                    <div>Lorem ipsum dolor sit amet...</div>#}
{#                </a>#}
{#                <div class="dropdown-divider"></div>#}
{#                <a href="#" class="dropdown-item">#}
{#                    <small class="text-muted">Lorem ipsum (yesterday)</small>#}
{#                    <br>#}
{#                    <div>Lorem ipsum dolor sit amet...</div>#}
{#                </a>#}
{#                <div class="dropdown-divider"></div>#}
{#                <a href="/docs/pages/content/notification.html" class="dropdown-item">#}
{#                    <small class="text-muted">Lorem ipsum (12/25/2017)</small>#}
{#                    <br>#}
{#                    <div>Lorem ipsum dolor sit amet...</div>#}
{#                </a>#}
{#                <div class="dropdown-divider"></div>#}
{#                <a href="#" class="dropdown-item dropdown-link">See all#}
{#                    notifications</a>#}
{#            </div>#}
{#        </li>#}
{#    </ul>#}
</nav>

main/templates/parts/meta.html
<meta name="theme-color" content="{{ data.themeColor }}">
<meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
<meta name="author" content="{{ data.author }}">
<meta name="copyright" content="{{ data.copyright }}">
<meta name="description" content="{{ data.description }}">
<meta name="keywords" content="{{ data.keywords }}">

main/templates/parts/sidebar-navigation.html
<div id="sidebar-nav" class="sidebar-nav">
    <ul>
        <li>
            <a href="#device-controls" data-toggle="collapse">
                <span class="sidebar-nav-icon fas fa-passport"></span>
                <span class="sidebar-nav-text">Documentation</span>
            </a>
            <ul id="device-controls" class="collapse" data-parent="#sidebar-nav">
{#                <li><a href="#"><span class="sidebar-nav-icon fas fa-robot"></span>Bot</a></li>#}
                <li><a href="{% url 'bot:func-docs' %}"><span class="sidebar-nav-icon far fa-file-code"></span>Functional</a></li>
            </ul>
            <hr>
        </li>
    </ul>
    <ul>
        <li>
            <a href="{% url 'bot:bot-create' %}">
                <span class="sidebar-nav-icon fas fa-hammer"></span>
                <span class="sidebar-nav-text">Create Bot</span>
            </a>
        </li>
{#        <li>#}
{#            <a href="#">#}
{#                <span class="sidebar-nav-icon fab fa-slack"></span>#}
{#                <span class="sidebar-nav-text">Bot Logs</span>#}
{#            </a>#}
{#        </li>#}
{#        <li>#}
{#            <a href="#">#}
{#                <span class="sidebar-nav-icon fas fa-file-alt"></span>#}
{#                <span class="sidebar-nav-text">Bot Docs</span>#}
{#            </a>#}
{#        </li>#}
    </ul>
    <hr>
    <ul>
        <li>
            <a href="#db" data-toggle="collapse">
                <span class="sidebar-nav-icon fas fa-database"></span>
                <span class="sidebar-nav-text">DB</span>
            </a>
            <ul id="db" class="collapse" data-parent="#sidebar-nav">
                <li><a href="{% url 'bot:bot-list' %}"><span class="sidebar-nav-icon fas fa-robot"></span>Existed bots</a></li>
                <li><a href="{% url 'bot:bot-data' %}"><span class="sidebar-nav-icon far fa-file-code"></span>Data</a></li>
                <li><a href="{% url 'bot:bot-code-list' %}"><span class="sidebar-nav-icon fas fa-vote-yea"></span>Existed code</a></li>
            </ul>
            <hr>
        </li>
    </ul>
{#    <ul>#}
{#        <li>#}
{#            <a href="{% url 'accounts:settings' %}">#}
{#                <span class="sidebar-nav-icon fa fa-cog"></span>#}
{#                <span class="sidebar-nav-text">Settings</span>#}
{#            </a>#}
{#        </li>#}
{#        <li>#}
{#            <a href="#">#}
{#                <span class="sidebar-nav-icon far fa-clock"></span>#}
{#                <span class="sidebar-nav-text">Timeline</span>#}
{#            </a>#}
{#        </li>#}
{#    </ul>#}
{#    <hr>#}
    <ul>
        <li><a href="{% url 'accounts:log-out' %}">
            <span class="sidebar-nav-icon fa fa-power-off"></span>
            <span class="sidebar-nav-text">Log out</span>
        </a>
        </li>
    </ul>
</div>