bot/urls.py
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from .views import *

app_name = 'bot'
urlpatterns = [
    path('doc/functional', bot_function_docs, name='func-docs'),
    path('list/', bot_list_view, name='bot-list'),  
    path('list/code', bot_code_list_view, name='bot-code-list'),
    path('create/', bot_create_view, name='bot-create'),
    path('update/<int:pk>', bot_update_view, name='bot-update'),
    path('delete/<int:obj_id>', bot_delete_view, name='bot-delete'),
    path('run/<int:pk>', run_bot, name='bot-run'),
    path('log/list', log_list, name='bot-log'),
    path('data/list', bot_data, name='bot-data'),
]

upt/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# import debug_toolbar
urlpatterns = [
    # path('__debug__/', include(debug_toolbar.urls)),
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
    path('', include('main.urls')),
    path('bot/', include('bot.urls')),
]

bot/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.


class Bot(models.Model):
    BOT_TYPE = (
        ('D', 'DEV'),
        ('P', 'PROD'),
    )
    BOT_STATE = (
        ('W', 'WORKING'),
        ('SP', 'STOPPED'),
        ('SR', 'STARTED'),
        ('F', 'FAILED'),
    )
    name = models.CharField(max_length=128, unique=True)
    type = models.CharField(max_length=1, choices=BOT_TYPE)
    currentState = models.CharField(max_length=2, choices=BOT_STATE, blank=True)
    link = models.URLField(blank=False)
    createdAt = models.DateTimeField(auto_now_add=True, blank=True)

    creator = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=True,
    )

    def __str__(self):
        return '{}'.format(self.name)

    class Meta:
        ordering = ['id']
        indexes = [
            models.Index(fields=['name', 'createdAt'])
        ]

    def get_absolute_url(self):
        return reverse('bot:bot-list')


class Code(models.Model):
    title = models.CharField(max_length=255, blank=True, null=True)
    code = models.TextField(blank=True, null=True)
    createdAt = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    modifiedAt = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    bot = models.ForeignKey(
        Bot,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )


class Data(models.Model):
    data = models.TextField(blank=True, null=True)
    bot = models.ForeignKey(
        Bot,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
    )


class Log(models.Model):
    LOG_LEVELS = (
        ('I', 'INFO'),
        ('W', 'WARNING'),
        ('E', 'ERROR'),
        ('S', 'SUCCESS'),
    )

    level = models.CharField(max_length=1, choices=LOG_LEVELS)
    createdAt = models.DateTimeField(auto_now=True,blank=True)
    message = models.TextField(blank=True, null=True)

    bot = models.ForeignKey(
        Bot,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
    )

    class Meta:
        ordering = ['-createdAt']

bot/forms.py
from django import forms
from .models import *


class BotForm(forms.ModelForm):
    class Meta:
        model = Bot
        fields = ['name', 'creator', 'type', 'link']

    def clean_creator(self):
        return self.cleaned_data['creator']

    def clean_name(self):
        data = self.cleaned_data['name']

        if Bot.objects.filter(name=data).exists():
            raise forms.ValidationError('A Bot name already exists. It mast be uniq.')

        return data


class BotFormUpdate(forms.ModelForm):
    disabled_fields = ('name', 'creator',)

    class Meta:
        model = Bot
        fields = ['name', 'creator', 'type', 'link']

    def __init__(self, *args, **kwargs):
        super(BotFormUpdate, self).__init__(*args, **kwargs)
        for field in self.disabled_fields:
            self.fields[field].disabled = True


class CodeForm(forms.ModelForm):
    class Meta:
        model = Code
        fields = ['title', 'code']

bot/views.py
import pdb

from main.util import Spider
from .forms import *
from django.contrib import messages
from django.http import JsonResponse, HttpResponseBadRequest
from django.template.loader import render_to_string
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage


def bot_list_view(request):
    object_list = Bot.objects.all()
    data = helper_for_pagination(request, Paginator(object_list, 10))

    if request.is_ajax():
        if request.GET.get('search'):
            text_to_search = request.GET.get('search')
            return JsonResponse(
                {
                    'type': 'search',
                    'response': render_to_string('bot/list/bot_element.html', {'object_list': Bot.objects.filter(
                        name__contains=text_to_search)})
                }
            )
        elif not request.GET.get('search'):
            data = helper_for_pagination(request, Paginator(object_list, 10))
            return JsonResponse(
                {
                    'type': 'default',
                    'response': render_to_string('bot/list/bot_element.html', {'object_list': data})
                }
            )
    return render(request, 'bot/list/bot_list.html', {'object_list': data})


def helper_for_pagination(request, p: Paginator):
    page = request.GET.get('page')

    try:
        data = p.page(page)
    except PageNotAnInteger:
        data = p.page(1)
    except EmptyPage:
        data = p.page(p.num_pages)
    return data


def bot_create_view(request):
    if request.method == 'POST':
        bot = BotForm(request.POST, prefix="bot")
        code = CodeForm(request.POST, prefix="code")
        if bot.is_valid() and code.is_valid():
            bot_obj = bot.save()
            messages.success(
                request,
                'Bot {} was created successfully!'.format(bot.cleaned_data['name'])
            )
            action = code.save(commit=False)
            action.bot = bot_obj
            action.save()
            messages.success(
                request,
                'Code for bot {} was created successfully!'.format(bot.cleaned_data['name'])
            )
            return redirect(reverse('bot:bot-list'))
    else:
        bot = BotForm(prefix="bot", initial={'creator': request.user, 'type': 'D'})
        code = CodeForm(prefix="code", initial={'code': 'Your code here :)'})

    return render(request, 'bot/bot_create.html', {'bot': bot, 'code': code})


def bot_update_view(request, pk: int):
    obj_bot = get_object_or_404(Bot, pk=pk)
    bot = BotFormUpdate(request.POST or None, instance=obj_bot, prefix="bot")

    obj_code = get_object_or_404(Code, bot=obj_bot)
    code = CodeForm(request.POST or None, instance=obj_code, prefix="code")

    if request.method == 'POST':
        if bot.is_valid() and code.is_valid():
            bot.save()
            code.save()
            messages.success(
                request,
                'Bot {} was updated successfully!'.format(bot.cleaned_data['name'])
            )
            return redirect(reverse('bot:bot-list'))

    return render(request, 'bot/bot_update.html', {'bot': bot, 'code': code})


def bot_delete_view(request, obj_id: int):
    obj = get_object_or_404(Bot, pk=obj_id)
    obj.delete()

    return redirect(reverse('bot:bot-list'))


def bot_code_list_view(request):
    object_list = Code.objects.all()
    data = helper_for_pagination(request, Paginator(object_list, 10))

    return render(request, 'code/list/code_list.html', {'object_list': data})


def bot_function_docs(request):
    s = Spider('')
    arr = []
    for func in s.get_all_funcs:
        arr.append(
            {
                'name': func,
                'doc': getattr(Spider, func).__doc__
            }
        )

    return render(request, 'documentation/index.html', {'object_list': arr})


def run_bot(request, pk: int):
    obj = get_object_or_404(Bot, pk=pk)
    code = Code.objects.get(bot=obj)

    existed_log = Log.objects.filter(bot_id=obj.id)
    if existed_log:
        for i in existed_log:
            i.delete()

    s = Spider(url=obj.link, id=pk)
    s._get_tree_from_request()
    try:
        s.parse(code.code)
    except:
        return redirect(reverse('bot:bot-log'))

    Data(bot_id=obj.id, data=s.data_to_json).save()
    Log(bot_id=obj.id, message=f'Bot {obj.name} completed his work', level='S').save()

    return redirect(reverse('bot:bot-log'))


def log_list(request):
    objs_list = Log.objects.all()

    return render(request, 'log/list/log_list.html', {'logs': objs_list})


def bot_data(request):
    obj_list = Data.objects.all()

    return render(request, 'data/list/list.html', {'object_list': obj_list})

bot/templates/bot/list/bot_element.html
{% for bot in object_list %}
    <tr>
        <td>{{ bot.id }}</td>
        <td>{{ bot.name }}</td>
        <td>{{ bot.get_type_display }}</td>
        <td>{{ bot.creator.username }}</td>
        <td>{{ bot.createdAt }}</td>
        <td>{{ bot.get_currentState_display }}</td>
        <td>
            <a class="edit-link" href="{% url 'bot:bot-update' pk=bot.id %}" title="Edit"><i
                    class="far fa-edit"></i></a>
            <form id='form-delete' method="POST" action="{% url 'bot:bot-delete' pk=bot.id %}">
                {% csrf_token %}
                <button class="remove-button" onclick="confirmDeletion()" title="Remove"
                        type="button">
                    <i class="fas fa-trash-alt"></i>
                </button>
            </form>
        </td>
    </tr>
{% empty %}
    <tr>
        <td align="center" colspan="7">Sorry, we have not data here :(</td>
    </tr>
{% endfor %}

bot/templates/bot/list/bot_list.html
{% extends 'default/index.html' %}

{% block title %}Bot List{% endblock %}
{% block breadcrumbs %}
    {% include 'parts/breadcrumbs.html' with next='Bot List' %}
{% endblock %}
{% block content-body %}
    <div class="container">
        {% if messages %}
            <div class="callout callout-info" id="opened">
                <h5>Done!</h5>
                {% for msg in messages %}
                    <p {% if msg.tags %} class="{{ msg.tags }}"{% endif %}>{{ msg }}</p>
                {% endfor %}
            </div>
        {% endif %}
        <div class="card">
            <div class="card-header">Bot List</div>
            <div class="form-group col-md-8 search">
                <input type="text" autocomplete="off" id="search-field" class="form-control"
                       placeholder="Searching by bot name">
            </div>
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Type</th>
                        <th>Creator</th>
                        <th>Created</th>
{#                        <th>State</th>#}
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody id="tbody">
                    {% for bot in object_list %}
                        <tr>
                            <td>{{ bot.id }}</td>
                            <td>{{ bot.name }}</td>
                            <td>{{ bot.get_type_display }}</td>
                            <td>{{ bot.creator.username }}</td>
                            <td>{{ bot.createdAt }}</td>
{#                            <td>{{ bot.get_currentState_display }}</td>#}
                            <td>
                                <a class="action-link" href="{% url 'bot:bot-update' pk=bot.id %}" title="Edit"><i
                                        class="far fa-edit"></i></a>
                                <a class="action-link" onclick="return confirm('Are you sure you want to delete this item?');"
                                   href='{% url 'bot:bot-delete' obj_id=bot.id %}' title="Remove">
                                    <i class="fas fa-trash-alt"></i>
                                </a>
                                <a class="edit-link" href="{% url 'bot:bot-run' pk=bot.id %}" title="Run"><i
                                        class="fas fa-play"></i></a>
                            </td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td align="center" colspan="7">Sorry, we have not data here :(</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="card-footer">
                {% include 'default/pagination.html' %}
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script>
        $("#search-field").on("keyup", e => {
            const {value} = e.target;
            $('#spinner').spinner('show');
            $.ajax({
                url: '{% url 'bot:bot-list' %}',
                data: {
                    search: value,
                    page: getUrlParameter('page')
                },
                type: 'GET'
            }).done(function (responseData) {
                if (responseData['type'] === 'search') {
                    $('.card-footer').hide();
                } else if (responseData['type'] === 'default') {
                    $('.card-footer').show();
                }
                $('#tbody').html(responseData['response']);
                $('#spinner').spinner('hide');
            }).fail(function () {
                console.log('Fail')
            });
        });
    </script>
{% endblock %}