accounts/urls.py
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from . import views

app_name = 'accounts'
urlpatterns = [
    path('log-in/', views.login, name='log-in'),
    path('log-out/', views.logout, name='log-out'),
    path('settings/', views.settings, name='settings'),
]

bot/urls.py
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from .views import *

app_name = 'bot'
urlpatterns = [
    path('doc/functional', bot_function_docs, name='func-docs'),
    path('list/', bot_list_view, name='bot-list'),  
    path('list/code', bot_code_list_view, name='bot-code-list'),
    path('create/', bot_create_view, name='bot-create'),
    path('update/<int:pk>', bot_update_view, name='bot-update'),
    path('delete/<int:obj_id>', bot_delete_view, name='bot-delete'),
    path('run/<int:pk>', run_bot, name='bot-run'),
    path('log/list', log_list, name='bot-log'),
    path('data/list', bot_data, name='bot-data'),
]

upt/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# import debug_toolbar
urlpatterns = [
    # path('__debug__/', include(debug_toolbar.urls)),
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
    path('', include('main.urls')),
    path('bot/', include('bot.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import auth


def login(request):
    args = dict()
    if request.POST:
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            args['profile'] = user
            return redirect('/', args)
        else:
            args['login_error'] = 'User not found!'
            return render(request, 'login/login.html', args)
    else:
        return render(request, 'login/login.html', args)


def logout(request):
    auth.logout(request)
    return redirect('/')


def settings(request):
    pass

accounts/templates/login/login.html
{% extends 'base.html' %}

{% load static %}
{% block title %}Sign In{% endblock %}
{% block body %}
    <div class="page-sign sign-in">
        <div class="container-sign">
            <div class="card">
                <div class="card-header">
                    {% if login_error %}
                        <div class="callout callout-danger">
                            <h5>Error</h5>
                            <p>{{ login_error }}</p>
                        </div>
                    {% endif %}
                    <h1>Welcome!</h1>
                    <span>Sign in to your account</span>
                </div>
                <div class="card-body">
                    <form action="{% url 'accounts:log-in' %}" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label>Username</label>
                            <input type="text" name="username" class="form-control">
                        </div>
                        <div class="form-group">
                            <label class="d-flex">
                                <div>Password</div>
                            </label>
                            <input type="password" name="password" class="form-control">
                        </div>
                        <div class="form-group d-flex">
                            <button type="submit" class="btn btn-primary ml-auto">Sign in</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}